// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tadmor.Core.Data.Services;

namespace Tadmor.Core.Migrations
{
    [DbContext(typeof(TadmorDbContext))]
    [Migration("20210820204005_Raffles")]
    partial class Raffles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Tadmor.Core.Bookmarks.Models.Bookmark", b =>
                {
                    b.Property<string>("ChatClientId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatClientId", "GuildId", "ChannelId", "Key");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Tadmor.Core.Data.Models.GuildPreferencesEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("GuildPreferences");
                });

            modelBuilder.Entity("Tadmor.Raffles.Models.RaffleExtraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExtractionTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RaffleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RaffleExtraction");
                });
#pragma warning restore 612, 618
        }
    }
}
