// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tadmor.Core.Data.Services;

namespace Tadmor.Core.Migrations
{
    [DbContext(typeof(TadmorDbContext))]
    [Migration("20210215034132_Add_Bookmarks_Entity")]
    partial class Add_Bookmarks_Entity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Tadmor.Core.Bookmarks.Models.Bookmark", b =>
                {
                    b.Property<string>("ChatClientId")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSeenValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChatClientId", "GuildId", "ChannelId", "Key");

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("Tadmor.Core.Data.Models.GuildPreferencesEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("GuildPreferences");
                });
#pragma warning restore 612, 618
        }
    }
}
