// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using Tadmor.Data;

namespace Tadmor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Tadmor.Data.GuildOptions", b =>
                {
                    b.Property<ulong>("Id");

                    b.Property<string>("CommandPrefix");

                    b.HasKey("Id");

                    b.ToTable("GuildOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
